### ISSUE TITLE
Payment sheet closes with "payment not completed" message

### ISSUE THREAD

**Issue by shatran** [tnguyen14/apple-pay-web-example#1]
Hi and thanks for this project.

After downloading the latest version of iOS10 beta, the payment sheet is being closed with a "payment not completed" message.
It happened on https://lab.tridnguyen.com/apple-pay-web-example/, not on a local machine.
Any idea why? has something changed with the new iOS version?

**Comment by tnguyen14** [comment]
Thanks for filing this. This was caused by a change in Safari and what it accepts from the startSession call. This has now been fixed.
