### ISSUE TITLE
Apple Pay buttons should not be rendered unless supported

### ISSUE THREAD

**Issue by martincostello** [tnguyen14/apple-pay-web-example#4]
Viewing the deployed application in Chrome on Windows 10 shows lots of empty black buttons.

The Apple Pay buttons should only be rendered if the browser supports ```ApplePaySession```.

**Comment by tnguyen14** [comment]
I kinda did this on purpose to verify the behavior on unsupported browsers. In a production environment, I would expect the button to not show.

However, for now, a browser would only support either the Payment Request API or Apple Pay JS, but not both (i.e. until Safari supports Payment Request API as well). So if you feel strongly about this change, let me know and I can update it.
