### ISSUE TITLE
ApplePay Sandbox test account

### ISSUE THREAD

**Issue by coder858** [tnguyen14/apple-pay-web-example#5]
Thanks for putting this example together. I stumbled upon it while troubleshooting my own implementation of ApplePay. Does https://lab.tridnguyen.com/apple-pay-web-example/ work with the ApplePay Sandbox? The ApplePay UI appears and disappears quickly on iPhone 7 (10.0.3) with my iTunes Connect acct.

Thanks!

**Comment by tnguyen14** [comment]
Hi thanks for the report. I'm aware of this issue, and am working on trying to fix it. Will post here when I have an update.

**Comment by coder858** [comment]
Thanks!

**Comment by tnguyen14** [comment]
Thanks for your patience. This should be fixed now.
